[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type =  application/javascript  
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"