# [build]
# command = "npm run build"
#  publish = "dist"

# [[headers]]
#  for = "/assets/remoteEntry.js"
#  [headers.values]
#    Content-Type = "application/javascript"
#    Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Expose-Headers = "*"
    Vary = "Origin"

[[headers]]
  for = "/remoteEntry.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS"
    Access-Control-Expose-Headers = "*"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS"
    Access-Control-Expose-Headers = "*"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"