



# [build]
#  command = "npm run build"
#  publish = "dist"

# [[headers]]
#  for = "/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
#    Access-Control-Allow-Methods = "GET,OPTIONS"

# [[headers]]
#  for = "/assets/remoteEntry.js"
#  [headers.values]
#    Cache-Control = "no-cache"



[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Content-Type = "application/javascript"  # ✅ Force correct MIME type
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"


