[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"