# [build]
# command = "npm run build"
#  publish = "dist"

# [[headers]]
#  for = "/assets/remoteEntry.js"
#  [headers.values]
#    Content-Type = "application/javascript"
#    Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/remoteEntry.js"
  to = "/assets/remoteEntry.js"
  status = 200

[[redirects]]
  from = "/assets/assets/*"
  to = "/assets/:splat"
  status = 200