



# [build]
#  command = "npm run build"
#  publish = "dist"

# [[headers]]
#  for = "/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
#    Access-Control-Allow-Methods = "GET,OPTIONS"

# [[headers]]
#  for = "/assets/remoteEntry.js"
#  [headers.values]
#    Cache-Control = "no-cache"



[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


