 # [build]
 # command = "npm run build"
 # publish = "dist"

 # [[headers]]
 # for = "/assets/remoteEntry.js"
   # [headers.values]
 #  Content-Type = "application/javascript"
  # Access-Control-Allow-Origin = "*"

# [build]
#   command = "npm run build"
#   publish = "dist"

# [[headers]]
#   for = "/*.js"
#   [headers.values]
#     Content-Type = "application/javascript"
#     Access-Control-Allow-Origin = "*"

# [[headers]]
#   for = "/*.css"
#   [headers.values]
#     Content-Type = "text/css"
#     Access-Control-Allow-Origin = "*"

# [[headers]]
#   for = "/remoteEntry.js"
#   [headers.values]
#     Cache-Control = "public, max-age=31536000, immutable"



[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Cache-Control = "no-cache"

