[build]
  command = "cd .. && rm -rf node_modules && npm install && cd music-library-app && npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"