[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"

   

