# [build]
#  command = "npm run build"
#  publish = "dist"

#  [[redirects]]
#    from = "/*"
#    to = "/index.html"
#    status = 200


[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
