[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }

[context.production.environment]
  VITE_MUSIC_LIBRARY_URL = "https://music-library-separate.netlify.app"

 

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
        Content-Type = "application/javascript; charset=utf-8"
