export const songs = [
  { id: 1, title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", year: 1975 },
  { id: 2, title: "Hotel California", artist: "Eagles", album: "Hotel California", year: 1976 },
  { id: 3, title: "Imagine", artist: "John Lennon", album: "Imagine", year: 1971 },
  { id: 4, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 5, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 6, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 7, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 8, title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", year: 1975 },
  { id: 9, title: "Hotel California", artist: "Eagles", album: "Hotel California", year: 1976 },
  { id: 10, title: "Imagine", artist: "John Lennon", album: "Imagine", year: 1971 },
  { id: 11, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 12, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 13, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 14, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 15, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 16, title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", year: 1975 },
  { id: 17, title: "Hotel California", artist: "Eagles", album: "Hotel California", year: 1976 },
  { id: 18, title: "Imagine", artist: "John Lennon", album: "Imagine", year: 1971 },
  { id: 19, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 20, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 21, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 22, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
   { id: 23, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 24, title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", year: 1975 },
  { id: 25, title: "Hotel California", artist: "Eagles", album: "Hotel California", year: 1976 },
  { id: 26, title: "Imagine", artist: "John Lennon", album: "Imagine", year: 1971 },
  { id: 27, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 28, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
  { id: 29, title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited", year: 1965 },
  { id: 30, title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", year: 1991 },
];